### ISSUE TITLE
Docs improvement for LB Hostnames

### ISSUE THREAD

**Issue by priteshkp** [terraform-providers/terraform-provider-oci#1055]
Similar to the example we give for Certificates:
https://www.terraform.io/docs/providers/oci/r/load_balancer_certificate.html

wrt the usage of `create_before_destroy`, it would be good to add that same example for Hostnames:
https://www.terraform.io/docs/providers/oci/r/load_balancer_hostname.html

A hostname cannot be updated if there is a Listener still using it, so the workaround is to set create_before_destroy (just like Certificates).  While I realized the problem and solution after a while, my first stop was the docs to see if I did something wrong, so it would have been helpful had it been there.

**Comment by rashik-bhasin** [comment]
Hi,
Can you share the terraform config that you are running and what you are trying to update exactly here. 
Are you only trying to update the hostname in this example: 
`resource "oci_load_balancer_hostname" "test_hostname" {
  #Required
  hostname         = "app.example.com"
  load_balancer_id = "${oci_load_balancer.lb1.id}"
  name             = "hostname"
  lifecycle {
    create_before_destroy = true
  }
}`

because when i tried to update the hostname for this I was able to update it just fine with a listener listing to this resource which is:

`resource "oci_load_balancer_listener" "lb-listener1" {
  load_balancer_id         = "${oci_load_balancer.lb1.id}"
  name                     = "http"
  default_backend_set_name = "${oci_load_balancer_backend_set.lb-bes1.name}"
  hostname_names           = ["${oci_load_balancer_hostname.test_hostname.name}"]
  port                     = 80
  protocol                 = "HTTP"
  rule_set_names           = ["${oci_load_balancer_rule_set.test_rule_set.name}"]

  connection_configuration {
    idle_timeout_in_seconds = "2"
  }
}`
Or are you trying to delete something simultaneously here? 
Thanks!

**Comment by rashik-bhasin** [comment]
Updated the documentation in terraform v3.81.0.
