### ISSUE TITLE
How do we manage protectionRules in TF

### ISSUE THREAD

**Issue by liberaworks** [terraform-providers/terraform-provider-oci#1093]
I could not find out just protection_rules in terrafrom.

How do we manage it in terraform?
Is there a special cause which it is not supported although there are custom protection policy…?

https://docs.cloud.oracle.com/en-us/iaas/Content/WAF/Reference/protectionruleids.htm

here is the list of resource TF is supporting now:
```
- name: addressLists
  path: addressLists/{addressListId}
  specVersionOverride: 1.2.962-fixed
- name: certificates
  path: certificates/{certificateId}
  specVersionOverride: 1.2.962-fixed
- name: customProtectionRules
  path: customProtectionRules/{customProtectionRuleId}
  specVersionOverride: 1.2.962-fixed
- name: edgeSubnets
  path: edgeSubnets
  specVersionOverride: 1.2.962-fixed
- name: httpRedirects
  path: httpRedirects/{httpRedirectId}
  specVersionOverride: 1.2.962-fixed
- name: purgeCache
  path: waasPolicies/{waasPolicyId}/actions/purgeCache
  specVersionOverride: 1.2.962-fixed
- name: waasPolicies
  path: waasPolicies/{waasPolicyId}
  specVersionOverride: 1.2.962-fixed
```

**Comment by alexng-canuck** [comment]
@liberaworks , I'm not sure where you got that list from, but custom protection rules are supported according to this: https://www.terraform.io/docs/providers/oci/r/waas_custom_protection_rule.html

Is this what you were looking for?

**Comment by liberaworks** [comment]
@alexng-canuck

**Comment by liberaworks** [comment]
@alexng-canuck 
thanks.
but it is not.

I'm looking for `Supported Protection Rules`.
https://docs.cloud.oracle.com/en-us/iaas/Content/WAF/Reference/protectionruleids.htm

Is it available to manage `Supported Protection Rules` with custom protection rules in TF?

**Comment by alexng-canuck** [comment]
@liberaworks , sorry for misunderstanding your original question.

I think you’re right that this is a feature gap in Terraform provider. Ideally, protection rules should have been specified as part of the WaaS policy resource like custom protection rules currently are. But because of the API design for this service, it does not give a way to update the protection rules when creating or updating a WaaS policy resource.

On the other hand, there may be another way to support this using UpdateProtectionRules APIs from service. I will file an enhancement request to investigate this.

**Comment by alexng-canuck** [comment]
@liberaworks , it sounds like this issue has already been mentioned and tracked here:
https://github.com/terraform-providers/terraform-provider-oci/issues/835

I will close this for now and we can use the original issue to track this enhancement.
