### ISSUE TITLE
Mismatch in oci tf variable name and attribute obtained in response of get_load_balancer(load_balancer_id, **kwargs) - python SDK

### ISSUE THREAD

**Issue by shruthi2703** [terraform-providers/terraform-provider-oci#1155]
There is a mismatch in the TF Variable name used to create the Load Balancer (ex: **shape**) and the attribute name got in the response of get_load_balancer(load_balancer_id, **kwargs)
(here it is shape_name)

TF Call:
```
resource "oci_load_balancer_load_balancer" "test_load_balancer" {
    #Required
    compartment_id = "${var.compartment_id}"
    display_name = "${var.load_balancer_display_name}"
    **shape** = "${var.load_balancer_shape}"
    subnet_ids = "${var.load_balancer_subnet_ids}"

    #Optional
    defined_tags = {"Operations.CostCenter"= "42"}
    freeform_tags = {"Department"= "Finance"}
    ip_mode = "${var.load_balancer_ip_mode}"
    is_private = "${var.load_balancer_is_private}"
    network_security_group_ids = "${var.load_balancer_network_security_group_ids}"
}
```

Response of get_load_balancer:
**shape_name**	[Required] Gets the shape_name of this LoadBalancer.

Ideally these two should be the same right? There is discrepancy here. Can the API/TF  attribute name also be changed to match each other?

We are trying to automate the export of the existing infrastructure based on the attribute values as specified in the TF creation.

**Comment by alexng-canuck** [comment]
Hi @shruthi2703,

We do not guarantee sameness between attribute names that are supported in Terraform and in other APIs/SDKs. Terraform is its own tool that is different from Python. 

Is it possible for your tooling to accommodate differences in attribute names?

Since you are exporting existing infrastructure, have you looked into using the resource discovery functionality of the Terraform provider? Link: https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/resource_discovery

Using the above tool, you do not need to worry about using Python and translating it into Terraform configs.

**Comment by shruthi2703** [comment]
Oh! thank you so much. I will have a look at it.

**Comment by alexng-canuck** [comment]
@shruthi2703 , I will take this offline with you.
