### ISSUE TITLE
VCN destroy goes to error when LPG is manually set

### ISSUE THREAD

**Issue by kviktorman** [terraform-providers/terraform-provider-oci#1160]
Hi,

I noticed a strange behaviour regards to VCN destroy.

I'm working on setting up two VCNs and connecting them via Local Peering Gateway (LPG). 
I have created the VCNs via terraform and did manually add the LPGs using the OCI web console (to see what additional resources do I need to create via terraform). 

When I triggered the destroy on one of the configured VCNs I have received the following error message:

```
Error: Service error:IncorrectState. ocid1.vcn... is associated with Local Peering Gateway that is in use. http status code: 409. Opc request id: ...
```

As a next try I went to the OCI web console and clicked on delete the same VCN, the VCN deletion process from there was successful. 

For me it seems that the OCI web console deletion process goes through all the linked objects, and deletes them which the terraform VCN deletion process doesn't seem to do.

I found it strange that we have two destroy processes and I'm a bit puzzled whether the two interfaces should follow the same process or not. 

Should be this the expected behaviour, if yes then are there any additional steps which I have to do before I can destroy the VCN via terraform?

Thanks, 
Viktor

**Comment by srishtipmishra** [comment]
@kviktorman - Terraform is a infrastructure management tool and the basic premise is, it can manage the infrastucture its state file contains. For reasons, if a resource is created via a different surface console in your case we call this a drift since terraform doesnt know about this resource. There are 2 scenarios in this case -
1. You changed a property of the resource like a tag value added to vcn - In this case running terraform refresh would be enough to bring the real state with tag value to terraform and you can add this new tag to your config to bridge the gap.

2. You add a different resource to your infrastructure - Local peering gateway in your case. This is an independent resource and vcn within your state has no knowledge of this. The correct way to resolve this drift is to use terraform import to import the LPG. This will update your state. Following this you'll need add LPG to your config and also cross reference(shown below) the vcn id in that config for terraform to know these are related. After this if you try to delete the vcn, terraform should delete the LPG too.

`/*resource "oci_core_local_peering_gateway" "test_local_peering_gateway_1" {
  #Required
  compartment_id = "${var.compartment_ocid}"
  vcn_id         = "${oci_core_vcn.vcn1.id}"  

  #Optional
  display_name = "localPeeringGateway1"
  peer_id      = "${oci_core_local_peering_gateway.test_local_peering_gateway_3_A.id}"
}`

As far as console is concerned, by design it knows about resources you create through any tool.

**Comment by kviktorman** [comment]
Hi @srishtipmishra,
I see, I was hoping for a different answer.

Thanks for the reply, I will continue the implementation as you described.

Cheers, 
Viktor

**Comment by srishtipmishra** [comment]
@kviktorman - Please reopen the issue if you need further help.
