### ISSUE TITLE
s3 remote_state stopped working

### ISSUE THREAD

**Issue by bieksaz** [terraform-providers/terraform-provider-oci#1177]
### Community Note

When running plan  I get the following error for each module. All modules have remote_state  defined as s3 object storage on oci. 

[terragrunt] [C:\FINWORK\terraform-qh-oci\dev\storage\object-storage] 2020/09/18 18:06:45 Module C:/FINWORK/terraform-qh-oci/dev/storage/object-storage has finished with an error: NotImplemented: S3 Get Bucket versioning configuration operation is not supported.
        status code: 501, request id: lhr-1:NbpQN0MVXHiIDewGPDB4URRLnrMZxRjYhqUAzQqgPhY9uTNFYmGweyjVos7IMkWC, host id:

This was working fine earlier, but recently it is no longer working, but coming out with an error.  

### Terraform Version and Provider Version

Terraform v0.12.28
terraform-provider-oci 3.62.0

### Terraform Configuration Files

example how remote_state is defined:

locals {
  common_vars      = read_terragrunt_config(find_in_parent_folders("common.hcl"))
}

remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
	bucket        = local.common_vars.locals.tfstate_bucket
	endpoint       = format ("https://%s.compat.objectstorage.%s.oraclecloud.com", local.common_vars.locals.namespace, local.common_vars.locals.region)
	key            = format("%s/terraform.tfstate", path_relative_to_include())
    region         = local.common_vars.locals.region
    encrypt        = true
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_get_ec2_platforms      = true
    skip_metadata_api_check     = true
    force_path_style            = true
  }
}

inputs = merge(
  local.common_vars.locals,
)

last successful build was tested on 2020.09.10 when it was still working. 

### Debug Output

plan output
https://gist.github.com/bieksaz/283e82f3dd37a8c0888f7e36bcb04b01#file-gistfile1-txt

### Expected Behavior

plan succeeds

### Actual Behavior

plan fails

### Important Factoids

no

**Comment by jotruon** [comment]
Hi @bieksaz ,
The API is not supported yet https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.GetBucketVersioning so service will return 501. 
You are seeing the error now because object storage just roll out a bug fix to return a real correctly return 501.

A workaround from service team is that you can config to **skip_bucket_versioning**  https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state 
`skip_bucket_versioning: When true, the S3 bucket that is created to store the state will not be versioned.`
Thanks,
John

**Comment by bieksaz** [comment]
Thanks, this helped with the issue
