### ISSUE TITLE
Security Lists : feature match with GUI - add posibility to declare list of ports with tcp_options and udp_options

### ISSUE THREAD

**Issue by kral2** [terraform-providers/terraform-provider-oci#586]
Using OCI Console, we can declare TCP/UDP ports using a mix of port range AND port list (e.g : 80, 20-21) with only one rule.

Terraform provider currently allow only to declare a range of ports (min and max attributes of tcp_options and udp_options). If the rule is not a strict contiguous list of ports, we must create another rule.

Using an array inside "tcp_options" may allow to declare something similar to 80, 20-21 with one rule in Terraform, as allowed with the console.

A proposition of syntax :

    ingress_security_rules = [
    {
      protocol = "6"
      source   = "${var.network_cidr["xxx"]}"

      tcp_options = [
        {
        min = "80"
        max = "80"
        },
        {
        min = "20"
        max = "21"
        }
      ]
    },
    ]

As soon as the "tcp_options" block of "ingress_security_rules" or "egress_security_rules" get a second pair of brackets, Terraform is returning this error :

    ingress_security_rules.0.tcp_options: attribute supports 1 item maximum, config has 2 declared

**Comment by hyder** [comment]
+1

**Comment by ravitandonrt** [comment]
Thank you for providing this feedback. We investigated this suggestion and have come to a conclusion, that while this is a good to have enhancement we will not be able to do at this time. 

Reasoning below:

* The Terraform Provider is based on the oci-go-sdk, which uses the APIs published by this service. The current behavior is in-line with what APIs and the SDKs do, that is one has to provide each ingress rule separately. The APIs below show that lists are only available IngressSecurityRules and EgressSecurityRules but not for TcpOptions or UdpOptions.
  * https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/SecurityList/CreateSecurityList
  * https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/datatypes/TcpOptions 
  * https://github.com/oracle/oci-go-sdk/blob/master/core/security_list.go#L44
  * https://github.com/oracle/oci-go-sdk/blob/master/core/ingress_security_rule.go#L59
  * https://github.com/oracle/oci-go-sdk/blob/master/core/tcp_options.go#L21
* I did a further investigation on how console was doing this, from the browser debugging tools it showed the expanded request which showed that they have additional logic created for making it easier, but still have code behind the scenes which is exactly doing what SDK/APIs need. That is, any entries made into those ranges with comma separation, are split and then multi-plexed to expand into what API is expecting.

This brings us to odds on what do we want to stay true to? The APIs or the Console simplicity? At this point, we are choosing to stay true/close to the actual underlying APIs as that allows us to reason more about the schema and further does not complicate the future story if APIs or Schema evolves. If we choose to do this, this becomes a very custom code to just improve a usability experience with no enhancement in functionality and may create future conflicts.

Hence, we have decided not to pursue this from Terraform provider perspective at this time, rather, work with the service team to share this feedback so that they can improve the APIs to accept such inputs than client tools having to do this logic.

**Comment by kral2** [comment]
Your explanation and choices totally makes sense. Let’s hope now for an API adaptation ;-)
