### ISSUE TITLE
Error when recreating instance with attached private IPs

### ISSUE THREAD

**Issue by geoffmorrison** [terraform-providers/terraform-provider-oci#613]
### Terraform Version

<details>
Terraform v0.11.8
</details>

### OCI Provider Version

<details>
terraform-provider-oci 3.1.0
</details>

### Description:
If I destroy and re-create an instance with associated secondary IPs, Terraform attempts to update the 
`vnic_id` of the`oci_core_private_ip` resource. However, destroying the instance also destroys the attached private IP, so the update operation fails.

A subsequent `apply` does notice that the resource is removed and re-create it. However, it takes two minutes per IP when refreshing the private_ip state to determine that the resource no longer exists.

Repro steps:

1.  `terraform apply`
2.  `terraform taint oci_core_instance.instance`
3.  `terraform apply`

Expected result:
A new instance is created, with a new secondary IP.

Actual result:
```
Error: Error applying plan:

1 error(s) occurred:

* oci_core_private_ip.secondary: 1 error(s) occurred:

* oci_core_private_ip.secondary: Service error:NotAuthorizedOrNotFound. Either Floating Private IP with ID ocid1.privateip.oc1.iad.abuwcljreiwt2xbrhwgqrnptwo6norjjrgua4bibp3vi6mbnbvg44jxuxi4a does not exist or you are not authorized to access it.. http status code: 404
```

### Terraform Plan

<details>

```
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "oci_api_key_path" {}
variable "fingerprint" {}
variable "provider_region" {}

variable "compartment_ocid" {}
variable "availability_domain" {}
variable "shape" {}
variable "image_ocid" {}
variable "subnet_ocid" {}

provider "oci" {
  version           = ">= 3.0.0"
  tenancy_ocid      = "${var.tenancy_ocid}"
  user_ocid         = "${var.user_ocid}"
  private_key_path  = "${var.oci_api_key_path}"
  fingerprint       = "${var.fingerprint}"
  region            = "${var.provider_region}"
}

resource "oci_core_instance" "instance" {
  compartment_id = "${var.compartment_ocid}"
  availability_domain = "${var.availability_domain}"
  
  shape = "${var.shape}"
  source_details {
    source_type = "image"
    source_id = "${var.image_ocid}"
  }
  
  create_vnic_details {
    subnet_id = "${var.subnet_ocid}"
    assign_public_ip = "false"
  }
}

data "oci_core_private_ips" "primary_private_ip" {
  subnet_id = "${oci_core_instance.instance.subnet_id}"
  ip_address = "${oci_core_instance.instance.private_ip}"
}

resource "oci_core_private_ip" "secondary" {
  vnic_id = "${lookup(data.oci_core_private_ips.primary_private_ip.private_ips[0], "vnic_id")}"
}
```
</details>

**Comment by alexng-canuck** [comment]
Hi @geoffmorrison,

Can you try adding this block inside your instance?

```
lifecycle {
  create_before_destroy = true
}
```

This will cause Terraform to create a new instance before destroying the old one. The secondary private IP can then be updated to be associated to the new instance, and should not be destroyed.

**Comment by ravitandonrt** [comment]
@geoffmorrison - We received a response from the Hashicorp engineering team that this scenario of associating dependencies with taint is not yet supported. It is a missing feature and while the Hashicorp core engineering is aware of it, there is no near-term solution.

Currently, only work-arounds are as suggested above. It is a special case because of the implicit deletes being done by the service. Another potential solution would be to prevent the instance from being deleted if there are any private_ips associated with it, but that will require the compute service to update its behavior and still may not be the solution you are looking for.

I am going to mark this issue closed for now as we have filed an issue with Hashicorp here for future feature request: https://github.com/hashicorp/terraform/issues/19050 

Re-listing the workarounds:
1. In addition to tainting an instance, please taint the secondary ip address as well. (Any dependencies that get implicitly deleted).
2. You can also use destroy with -target that will remove this resource and dependencies, and then apply
3. Lastly, the option you have been doing, re-apply.

**Comment by F21** [comment]
Encountered this myself recently. I was able to work around it by using a `lifecycle` block like so:

```hcl
resource "oci_core_private_ip" "vault_cloudflared" {
  ip_address = "10.1.1.2"
  vnic_id    = var.vnic_id

  lifecycle {
    replace_triggered_by = [
      oci_core_instance.my_instance
    ]
  }
}
```
