### ISSUE TITLE
oci_database_autonomous_data_warehouse_wallet returns all data warehouse of a tenancy

### ISSUE THREAD

**Issue by vbuddi** [terraform-providers/terraform-provider-oci#651]
### Terraform Version

Terraform v0.11.8

### OCI Provider Version

 provider.oci v3.7.0

### Description:
tnsnames.ora which is part of wallet returned by oci_database_autonomous_data_warehouse_wallet contains the details of all the autonomous data warehouses in the tenancy.
tnsnames.ora should contain the details of only the autonomous data warehouse which is provided as input to the wallet data source.
### Terraform Plan
Here is my code--
resource "oci_database_autonomous_data_warehouse" "test_autonomous_data_warehouse" {
  #Required
   admin_password = "${var.passwd}"
   compartment_id = "${var.cmp_id}"
   cpu_core_count = "1"
   data_storage_size_in_tbs = "1"
   db_name = "MyADW"
 }

data "oci_database_autonomous_data_warehouse_wallet" "autonomous_data_warehouse_wallet" {
  #Required
  autonomous_data_warehouse_id = "${oci_database_autonomous_data_warehouse.test_autonomous_data_warehouse.id}"
  password                     = "${var.passwd}"
}

resource "local_file" "autonomous_data_warehouse_wallet_file" {
  content  = "${data.oci_database_autonomous_data_warehouse_wallet.autonomous_data_warehouse_wallet.content}"
  filename = "./ADW_wallet.zip"
}

The above code outputs the wallet with tnsnames.ora containing all the autonomous data warehouse details of the tenancy.

**Comment by rcohenma** [comment]
Thank you for your feedback.
We think this is an issue with the service and not with the terraform provider.
We have passed on the information to the relevant service.
We will update this ticket when they give us an update

**Comment by ravitandonrt** [comment]
@vbuddi and @thehhugg We had followed up with the service they said that this is the expected behavior of the API. There will be future enhancements to provide API for creating/revoking a single PDB wallet.

With regards to security concern, the .ora file contains only the names of the databases, following is response from the team:
*Customer needs to present wallet plus database user credential to login to database.  The credential is per database.*
