### ISSUE TITLE
Security Lists: allow interpolation by turning options attributes into maps

### ISSUE THREAD

**Issue by lucianf** [terraform-providers/terraform-provider-oci#665]
Understanding from #586 that it will not be possible (at least in the near future) to define multiple ports per rule; in the interest of brevity (making configuration cleaner), would it be possible to make the `tcp_options_`/`udp_options`/`icmp_options` attributes into maps, so that they can be interpolated from variables or locals?

In other words I'm suggesting that instead of:
```
egress_security_rules = [
    {
      protocol    = "6"
      destination = "0.0.0.0/0"

      tcp_options {
        "min" = 443
        "max" = 443
      }
    },
    {
      protocol    = "6"
      destination = "0.0.0.0/0"

      tcp_options {
        "min" = 443
        "max" = 443
      }
    }
  ]
```
we could do something like:
```
locals {
	known_ports = {
		https = {
			"min" = 443
			"max" = 443
		},
		http = {
			"min" = 80
			"max" = 80
		}
	}
}

egress_security_rules = [
    {
      protocol    = "6"
      destination = "0.0.0.0/0"

      tcp_options = "${local.known_ports["https"]}"
    },
    {
      protocol    = "6"
      destination = "0.0.0.0/0"

      tcp_options = "${local.known_ports["http"]}"
    }
  ]
```

**Comment by ravitandonrt** [comment]
@lucianf Thanks for reporting on the usage semantics. 

What you suggest also comes down to having a different type (map) for TcpOptions for egressSecurityRules and ingressSecurityRules - which today is a 1:1 mapping on how the APIs are (also detailed in originally quoted issue): https://github.com/oracle/oci-go-sdk/blob/893b72e14683a665d30e3cd1f226c014df1277d5/core/egress_security_rule.go#L60
 
This maybe relevant feedback for the service to improve their APIs and we will pass on that, but would not be able to accommodate aesthetic changes that are different from APIs as that creates an API gap and tougher to maintain as APIs evolve because many people would have existing TF configs that will likely break.

I also have a different news in this regard to you, with upcoming Terraform 0.12 release early next year, it is adopting a newer format (hcl2 syntax) of specifying this, which maybe even more verbose. They are likely going to provide an upgrade tool which will update existing Terraform 0.11.x configurations to newer formats.

Here is a the link to that issue: https://github.com/hashicorp/terraform/issues/19407

At this point, we would wait on the hcl2 syntax to land with Terraform 0.12 as that is likely going to change this specification format for TypeSets/Maps i.e. Security Lists and then figure out alternatives within the confines of API compatibility.
