### ISSUE TITLE
Auto Deletion of OCI resources

### ISSUE THREAD

**Issue by psaddi** [terraform-providers/terraform-provider-oci#667]
This is more of a request  than an issue ( https://www.terraform.io/docs/providers/oci/d/identity_compartment.html)

Clearly there is no way to delete all resources given a compartment. We are setting up an application for Sales demo workforce to help use auto resource creation for them to create official demos for customers. However we plan to provide the tenancies for a certain time only. If they are forced to use only our recipes using terraform we could easily use the state to delete all the resources. However to allow complete flexibility they could really use any resource manager tools to manage resources.

Now I would like to request if there is a way to accept an Enhancement to delete all resources in a compartment, given a tenancy and compartment. 

If that is not possible, are there any recommendations to plan this feature. The only option I have is to search for every resource documented in terraform, and see if a compartment has any of these resources and create a dependency plan amongst them, and use oci or terraform to clean them up.

Appreciate your feedback

**Comment by ravitandonrt** [comment]
We appreciate the time you took to write to us @psaddi 

This request has been voiced before when the compartment delete feature came out, however due to the current API design constraints and principles (prevent customers from accidental removal) that option is not available. From a Terraform provider perspective we cannot commit or provide support for that scenario. For a live production systems, accidentally destroying entire cloud inventory is a significant risk, even if such a removal was intentional, for e.x. one compartment maybe hosting resources attached to another compartment (think VNICs).

One of the alternatives that has been suggested, is to build something similar to this project: https://github.com/dtan4/terraforming for OCI resources. This request is under consideration but no updates on that.

The current possible work-around is to use Ansible Inventory script from the OCI Ansible repository -> https://github.com/oracle/oci-ansible-modules/blob/master/inventory-script/oci_inventory.py

Whether it's Ansible Inventory script or Terraforming, the tools will only be able to recognize the resources which the particular provider supports, that does not necessarily equate to every resource that may actually exist.

**Comment by psaddi** [comment]
Exporting Terraform state given a compartment, would definitely be a nice workaround if that could be achieved, but thank you for responding with certain options
