### ISSUE TITLE
Support for consistent device paths for block volumes

### ISSUE THREAD

**Issue by olkoko** [terraform-providers/terraform-provider-oci#689]
### Description:
Need support for attaching block volumes with consistent device paths.
More details [here](https://docs.cloud.oracle.com/iaas/Content/Block/References/consistentdevicepaths.htm).

**Comment by kilokahn** [comment]
Hello @olkoko - this is slated to be released tomorrow. I will update the ticket once the release is completed.

**Comment by kilokahn** [comment]
Hello @olkoko - the feature is released in the v3.12.0 of the provider today. Let us know if you face any difficulties in using it. See https://www.terraform.io/docs/providers/oci/r/core_instance.html#is_consistent_volume_naming_enabled for the usage

**Comment by svilmune** [comment]
This is really good feature so thanks! How do we specify the attached block volume then which device path it uses? In the documentation you specify the path during attachment but I don't see similar option in the oci_core_volume_attachment ?

**Comment by kilokahn** [comment]
The `device_name` attribute of `oci_core_volume_attachment` shoudl help you. See https://www.terraform.io/docs/providers/oci/r/core_volume_attachment.html#device and https://docs.cloud.oracle.com/iaas/Content/Block/References/consistentdevicepaths.htm for more details. If you have any other questions, feel free to open up a new github issue so that we can address it promptly!
