### ISSUE TITLE
Tagging Namespace & Tag Immutability

### ISSUE THREAD

**Issue by rramge** [terraform-providers/terraform-provider-oci#704]
### Terraform Version

Terraform v0.11.11

### OCI Provider Version

+ provider.oci v3.14.0

### Description:

Tagging Namespaces and Tags are defined as being immutable - you cannot change or delete them after creation, you can only retire them (except for one potentially unintended scenario, I will mention this later in this ticket).

Okay, you can't change or delete them. But terraform does not know and the oci provider happily tries to change or delete them if a change seems to make this necessary. For example, if you move an already existing tagging namespace into a module, Terraform tries to delete the existing namespace and re-create it from scratch with the old name. Which will then lead to an OCI error message, terraform failing and a state which needs manual fixing. I ran into this issue two times within the last week, so I consider this being a rather ugly trap.

I think it would be great to introduce a "enable_delete" flag for tagging namespaces, similar to compartments. This should also affect the tags which are assigned to this namespace. Default should be "false". Setting it to "true" should only result in deleting the tagging namespace or tag from the statefile instead of being sent to the API, if that's possible.

The problem is that there is a way how a tagging namespace and tag can get deleted: By deleting the compartment which contains the namespace. 
This seems to be a quite stressful thing for OCI, I just tried it and the deletion work request is already running for over 90 minutes and terraform timed out multiple times by now... wouldn't be surprised if this will end in a MOS ticket at some point. But this is the case where the "enable_delete = true" might be useful, because otherwise we might run into a dependency problem.

Of course, I hope someone else has a more monkey-proof idea how to approach this. Fixing OCI and allowing tagging namespaces to be deleted would be the best solution in my opinion...

Ralf

**Comment by ravitandonrt** [comment]
Thanks for sharing your thoughts @rramge and I empathize with your frustration on the surprise/expectation of the API behavior.

There are two properties that do allow you to manage the resource behavior you are noticing (mentioned below). It does fall back to your usage or expectation, as moving resources out of a Terraform config will result in a destroy.

Since you don't want Terraform to destroy those resources, one workflow would be to use `terraform state rm` to remove from state file and then when module is used, to import it, `terraform import resource.name resource.ocid`

Alternatively, you can leverage these two properties, one belongs to the tag_namespace resource:

`is_retired` - https://www.terraform.io/docs/providers/oci/r/identity_tag_namespace.html#is_retired

The other property is by Terraform that prevents destroy to trigger.

`prevent_destroy` - https://www.terraform.io/docs/configuration/resources.html#prevent_destroy

Adding `enable_delete` is syntax sugar to hide assumptions that may vary from customer to customer.

I am tagging this as an enhancement on our end to consider if it makes sense. We try to be cautious when considering customization on top of existing APIs unless it is unavoidable. Do let us know if any of the above two options do not work out for you.

**Comment by rramge** [comment]
Hi,

I am back at this topic again and would like to propose an improvement which is necessary in my opinion. Please improve the oci provider by NOT allowing tag namespaces and tags being destroyed or modified.  

Retiring the resource should be okay, but destroying or modifying it mustn't be. 

'terraform destroy' currently will try to destroy the tag namespaces and tag definitions, even though destroying them is not possible:

--- 8< ---
[ralf@olinux7 terraform]$ terraform destroy
data.terraform_remote_state.oci_object_storage: Refreshing state...
oci_identity_tag_namespace.costs: Refreshing state... (ID: ocid1.tagnamespace.oc1..aaaaaaaahfpktjl...flnl5uveceben4dzpvluiftmhayqb6f6aaywja)
[...]
Terraform will perform the following actions:

  - oci_identity_compartment.c001

  - oci_identity_compartment.c002

  - oci_identity_compartment.s3compatible

  - oci_identity_tag.client

  - oci_identity_tag_namespace.costs
[...]
--- 8< ---
This leads to an inconsistency which requires manual fixing the terraform state (by manually importing the affected resources) and the terraform configuration (by adding prevent_destroy). Until now, the REST API does NOT send an error back, and I doubt it ever will.  It just stays quiet. Thus, Terraform will assume that the operation went okay even though it didn't.

I think it is very unlikely that anyone will add "prevent_destroy" proactively and before running into a problem here. 

When disallowing the destroying of a namespace, it would also automatically keep terraform from destroying compartments with a tagging namespace inside of them.

Please, please, please with cherry on top, let's make this monkey-proof.

Cheers,

Ralf

**Comment by afedorch** [comment]
@rramge  
Support for defined tags and tag namespace deletion was introduced as part of the v3.28.0 release. 
The inconsistency that you mentioned should be resolved: `identity_tag_namespace` and `identity_tag` resources will be removed from the state file only if corresponding resources were successfully destroyed on the cloud. I am closing this request please feel free to open the issue if the behavior of the resources differs from the expected one. thanks!
Deleting Tag Key Definitions and Namespace: https://docs.cloud.oracle.com/iaas/Content/Identity/Concepts/taggingoverview.htm#deleting
