### ISSUE TITLE
oci_database_db_system - Unable to process JSON input

### ISSUE THREAD

**Issue by llBIKSll** [terraform-providers/terraform-provider-oci#710]
### Terraform Version

<details>
# Run this command to get the terraform version:

$ terraform -v

Terraform v0.11.11

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci

provider.oci v3.14.1

### Description:
Terraform init - No error
Terraform plan - No error
Terraform apply - Error
Error: Error applying plan:

1 error(s) occurred:

* oci_database_db_system.dev_db_system: 1 error(s) occurred:

* oci_database_db_system.dev_db_system: Service error:InvalidParameter. Unable to process JSON input. http status code: 400. Opc request id: d85389a
6363a/9E41167CAC9D40E620CBF4FE26DC3B42/CDF1EC4D61F208B92AC74F2FEBEE0522

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.
provider "oci" {
  tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaaipgwoysaccyierea2ypvnnoak2hnx4o4jqfdxxxxxxxxxxxxxxxx"
  user_ocid = "ocid1.user.oc1..aaaaaaaaihdcrqey5445rnoaxb2vir32atwur7xxxxxxxxxxxxxxxxxxx"
  fingerprint = "45:0e:86:b9:0d:34:65:d7:3a:04:74:59:22:xx:xx:xx"
  private_key_path = ".\\.oci\\oci_api_key.pem"
  region = "eu-frankfurt-1"
}

resource "oci_database_db_system" "dev_db_system" {
    #Required
    availability_domain = "orBF:EU-FRANKFURT-1-AD-1"
    compartment_id = "ocid1.compartment.oc1..aaaaaaaaxwpjh3ahcxmkdrimeo5ehkhx4ekizxcjwxcjxxxxxxxxxxxxx"
    database_edition = "Enterprise Edition"
    db_home {
        #Required
        database {
            #Required
            admin_password = "_u0G3_4vCV7M_" #temp password

            #Optional
            #backup_id = "${oci_database_backup.test_backup.id}"
            #backup_tde_password = "${var.db_system_db_home_database_backup_tde_password}"
            #character_set = "${var.db_system_db_home_database_character_set}"
            /*db_backup_config {

                #Optional
                auto_backup_enabled = "${var.db_system_db_home_database_db_backup_config_auto_backup_enabled}"
            }*/
            db_name = "devdb"
            #db_workload = "${var.db_system_db_home_database_db_workload}"
            #defined_tags = "${var.db_system_db_home_database_defined_tags}"
            #freeform_tags = "${var.db_system_db_home_database_freeform_tags}"
            #ncharacter_set = "${var.db_system_db_home_database_ncharacter_set}"
            pdb_name = "devpdb"
        }

        #Optional
        db_version = "12.1.0.2"
        display_name = "devdb"
    }
    hostname = "dbhost"
    shape = "VM.Standard2.2"
    ssh_public_keys = [".\\.ssh\\id_rsa.pub"]
    subnet_id = "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaahaf7ekpejofbpdxvxvzprdilzatsfay7yg76i2lfxxxxxxxxxxxx"

    #Optional
    #backup_subnet_id = "${oci_database_backup_subnet.test_backup_subnet.id}"
    #cluster_name = "${var.db_system_cluster_name}"
    #cpu_core_count = "${var.db_system_cpu_core_count}"
    #data_storage_percentage = "${var.db_system_data_storage_percentage}"
    #data_storage_size_in_gb = "${var.db_system_data_storage_size_in_gb}"
    #defined_tags = {"Operations.CostCenter"= "42"}
    #disk_redundancy = "${var.db_system_disk_redundancy}"
    #display_name = "${var.db_system_display_name}"
    #domain = "${var.db_system_domain}"
    #freeform_tags = {"Department"= "Finance"}
    #license_model = "${var.db_system_license_model}"
    node_count = "2"
    #source = "${var.db_system_source}"
    #sparse_diskgroup = "${var.db_system_sparse_diskgroup}"
}

**Comment by rcohenma** [comment]
Hello,
Thanks for reporting this
This is a 400 error from the service so it means that you are passing the wrong combination of parameters.

The service should provide a better error message so that a user would be better able to understand whats wrong and how to fix it. I've opened a ticket with the service and i'm awaiting their reply to see if they can provide any help on this.

In the mean time you can read the documentation and try to find if any parameters you are passing don't match what the documentation requires. https://www.terraform.io/docs/providers/oci/r/database_db_system.html

i checked that our example works fine: https://github.com/terraform-providers/terraform-provider-oci/tree/master/docs/examples/db_systems

**Comment by rcohenma** [comment]
Here are some things i noticed from your terraform config:
1. it seems that for the ssh_key you are passing the file name instead of the actual key.

you can specify it like we do in the example
ssh_public_keys = ["${var.ssh_public_key}"]

and load it in your environment like this
export TF_VAR_ssh_public_key=$(cat ~/.ssh/key.pub)

2. you are using hard coded values for the version and the shape
You should use the available datasources to make sure the service supports that combination of values in your availability domain
https://www.terraform.io/docs/providers/oci/d/database_db_system_shapes.html
https://www.terraform.io/docs/providers/oci/d/database_db_versions.html

**Comment by llBIKSll** [comment]
Thanks for the help. I am aware of the hardcoding stuff. But is ok to try it out.
@rcohenma , thanks for point it out,  I am now using "${file(".\\.ssh\\id_rsa.pub")}"

The main issue was solved by having the right edition in place. in my case where I like to have RAC I need to set the edition to  database_edition = "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"

Other discoveries
data_storage_size_in_gb  - it is not option in this case

**Comment by llBIKSll** [comment]
Issue Solved.
