### ISSUE TITLE
* provider.oci: can not create client, bad configuration: did not find a proper configuration for private key

### ISSUE THREAD

**Issue by matthbak** [terraform-providers/terraform-provider-oci#712]
### Terraform Version

<details>
$ terraform -v
Terraform v0.11.11
+ provider.oci v3.14.1

</details>

### OCI Provider Version

<details>
11:49 $ .terraform/plugins/linux_amd64/terraform-provider-oci_v3.14.1_x4 
2019/02/12 11:49:36 [INFO] terraform-provider-oci 3.14.1
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

</details>

### Description:
When using an encrypted private key I get the bad config error shown below:

<details>
Error: Error refreshing state: 1 error(s) occurred:

* provider.oci: can not create client, bad configuration: did not find a proper configuration for private key
</details>

If I decrypt the key and set the TF_VAR_private_key_password to blank it works.
Moving the key file to a sub-directory of the terraform working directory does not help.
An unencrypted key outside the working directory works.

### Terraform Plan

Using this terraform file
<details>
# main.tf
resource "oci_identity_compartment" "networks" {
  provider    = "oci.fra"
  name        = "networks"
  description = "Network Compartment"
}

provider "oci" {
  region               = "eu-frankfurt-1"
  alias                = "fra"
  tenancy_ocid         = "${var.tenancy_ocid}"
  user_ocid            = "${var.user_ocid}"
  fingerprint          = "${var.fingerprint}"
  private_key_path     = "${var.private_key_path}"
  private_key_password = "${var.private_key_password}"
  version              = ">= 3.14.0"
}

terraform {
  backend "artifactory" {
    username = "*******@oracle.com"
    url      = "https://artifactory/"
    repo     = "tf"
    subpath  = "network"
  }
}

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "private_key_password" {}
</details>

## Env vars
<details>
    export TF_VAR_user="matthew.x.baker@oracle.com";
    export TF_VAR_region="eu-frankfurt-1";
    export TF_VAR_identity_domain="******";
    export TF_VAR_endpoint="https://console.eu-frankfurt-1.oraclecloud.com";
    export TF_VAR_user_ocid="ocid1.user.oc1..*******";
    export TF_VAR_tenancy_ocid="ocid1.tenancy.oc1..*******";
    export TF_VAR_fingerprint="a3:f3:89:7d:ae:91:16:01:3c:95:84:ff:b1:56:37:08";
    export TF_VAR_private_key_path="/home/matthbak/.oci/oci_api_key.pem";
    export TF_VAR_private_key_password="***********";
    export TF_VAR_ssh_public_key="$(cat ~/.ssh/id_rsa.pub)"
</details>

## OS env
Linux matthbak-laptop 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by matthbak** [comment]
Note this works, same tfvars (obvs diff ocids) and tf file, for a different tenancy. This tenancy is in eu-frankfurt-1 and is using federated identity management if that makes a difference? I notice from the logs that issue #709 also is in eu-frankfurt-1. Coincidence?

**Comment by bowfeng** [comment]
@matthbak I couldn't reproduce your error. how did you generate private key? Are you following this https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#How

**Comment by matthbak** [comment]
Yes. I am using the same key that works in another env and works with this env without the encryption. I presume this is happening locally when the key is being decrypted in the client. It works with the encrypted key with the oci cli.

**Comment by alexng-canuck** [comment]
@matthbak are you still blocked by this issue?

**Comment by matthbak** [comment]
I am not blocked by it but it is not resolved. I do not experience it elsewhere in OCI. It is less than desirable to need to decrypt my key to use the env.

**Comment by ravitandonrt** [comment]
@matthbak We have not seen this issue reported by other users, as per what you have said, this maybe a local environment configuration issue.

Since we have been unable to reproduce this, from how the SDK clients are loaded and configured, there maybe one another reason/bug - OCI profiles.

**Do you have a OCI Setup config (via CLI) that has multiple profiles where a default profile maybe different than the profile you are running, both of which may have different keys?**

The provider uses the DEFAULT profile loading in addition to TF_VAR variables by using a ComposingConfigurationProvider that loads them in order of how configuration providers are specified. I want to understand if this could be the reason for this. The error is coming from SDK, and another profile maybe interfering possibly leading to this error.

My suggestion would be to align your TF_VAR values with the DEFAULT profile and try it out.

References:
* https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/provider.go#L720
* https://github.com/oracle/oci-go-sdk/blob/master/common/client.go#L175
* https://github.com/oracle/oci-go-sdk/blob/master/common/configuration.go#L534

**Comment by matthbak** [comment]
@ravitandonrt Thanks for your detailed answer.

I have a single '~/.oci/config' file. In that file are multiple profiles. There is no "DEFAULT" profile.
In terraform there is no profile name given as part of the loading of the provider. I use TF_VARs exclusively to configure terraform.

Using the code you reference I have called the function to get the key:
`package main

import (
    "fmt"
    oci_common "github.com/oracle/oci-go-sdk/common"
)

func main() {
    provider := oci_common.DefaultConfigProvider()
    fmt.Print(provider.PrivateRSAKey())
}
`

`
$ go run main.go 
<nil> did not find a proper configuration for private key(0) matthbak@matthbak-laptop ~/Projects/oci_bug
$ set_ccesharedsvceu     # <- sets env TF_VARS
(0) matthbak@matthbak-laptop ~/Projects/oci_bug
$ go run main.go 
&{{287...537} 182...825 [173...1173] {157...644 []}} <nil>(0) matthbak@matthbak-laptop ~/Projects/oci_bug
$ 
`

I presume that suggests that it is able to find the key when the env vars are set but the default config does not contain a key.

**Comment by varmax2511** [comment]
Hi @matthbak . Per provider workflow, this error is generated only in scenarios where an incorrect password is used to decrypt the key. I assume that the key is correct but is getting overridden by multiple configurations present in your local environment. 

Its possible that you might be setting both `private_key` and `private_key_path`, one via tfvars and other via `.oci/config`. `private_key` takes precendence over `private_key_path`
https://www.terraform.io/docs/providers/oci/index.html#private_key

Alternatively, a quick way to validate would be to backup all the OCI configuration in `/.oci` folder and rename/move them. Remove any environment variable settings. Pass the config directly in the provider for the `private_key_path` and `private_key_password` variables. Since this will be the only source, the correct key and password will propagate. If this works, you can work backwards by enabling the configurations and identifying the override. 

Please let us know if this helps.

**Comment by matthbak** [comment]
Done as you suggested and moved ~/.oci directory out of the way.

`12:02 $ cat provider.tf 
provider "oci" {
  alias                = "fra"
  // tenancy_ocid         = "${var.tenancy_ocid}"
  // user_ocid            = "${var.user_ocid}"
  // fingerprint          = "${var.fingerprint}"
  // private_key_path     = "${var.private_key_path}"
  // private_key_password = "${var.private_key_password}"
  tenancy_ocid         = "ocid1.tenancy.oc1..aaaaaa**********vq"
  user_ocid            = "ocid1.user.oc1..aaaa***********oq"
  fingerprint          = "a3:**********:08"
  private_key_path     = "/home/matthbak/.oci.orig/oci_api_key.pem"
  private_key_password = "**********"
  region               = "eu-frankfurt-1"
  version              = ">= 3.30.0"
}
`
Added the tenancy_ocid var for other resources. Then did a plan.

Output:
`Error: Error refreshing state: 1 error(s) occurred:

* provider.oci: can not create client, bad configuration: did not find a proper configuration for tenancy
`

This is a different error to before. I replaced the env var for tenancy_ocid and then it complained about user. I had a thought to remove the alias from the provider, a module call and a data resource, as it made me think that is might be assuming some defaults and sure enough it worked. I moved everything back and it's working without the alias. 

So could there be something in the way provider aliases work that would prevent the private key password from being used?

**Comment by varmax2511** [comment]
You are getting the below error even though tenancy information is supplied, because either you have declared two providers in your config each using different configuration or some of the resources in your config are not referring to the provider alias `oci.fra`, causing Terraform to implicitly create a default provider for you.

```hcl
Error: Error refreshing state: 1 error(s) occurred:

* provider.oci: can not create client, bad configuration: did not find a proper configuration for tenancy
```

When the alias is removed from your provider config, Terraform treats the supplied provider as the default provider and uses the values passed. Since desired key and password are supplied, it works!

Assuming you have only one provider declared in your config. When you add an alias to the provider and if even one of the resources is not explicitly specifying the provider alias via `provider = "oci.fra"`, then for these resources terraform creates a default provider other than your alias provider. The default provider loads configuration from /.oci or env variables. These variables may be supplying a different key or a different password causing failures.

I would suggest either removing the alias in your config or every resource should specify the provider alias it wants to use. Please let us know if this helps.

**Comment by matthbak** [comment]
Yes removing the alias seemed to be what worked in the end. However, I suggest there still might be an issue somewhere as why was the encrypted key not accepted in the first place? Recapping what was there in configuration originally:

* ./oci/config contains no defaults section only named profiles
* TF_VAR_* environment variables setting all appropriate configuration
* a default provider and an alias provider instance of oci.fra

So I think the default provider was not receiving the passphrase through the environment variable TF_VAR_private_key_password. Looking at the documentation it does suggest it does not accept that env var.
https://www.terraform.io/docs/providers/oci/index.html#environment-variables

If I am correct, I wonder if this is more a limitation of the underlying oci go module than with the terraform provider? Should the env var for private key password work?

If I comment out all of the configuration of the provider like so:

```
provider "oci" {
  region = "eu-frankfurt-1"
  version = ">= 3.30.0"
}
```

And use env vars for my unencrypted key, it works:

```
TF_VAR_endpoint=https://console.eu-frankfurt-1.oraclecloud.com
TF_VAR_fingerprint=a3:********:08
TF_VAR_private_key_password=
TF_VAR_private_key_path=/home/matthbak/.oci/oci_api_key_unencrypted.pem
TF_VAR_region=eu-frankfurt-1
TF_VAR_tenancy_ocid=ocid1.tenancy.oc1..aaaaa********q
TF_VAR_user_ocid=ocid1.user.oc1..aaaaa********q
```

If I then change the key_path to the encrypted key and add the password to the env var it doesn't work. I get:

```
14:59 $ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.common: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* provider.oci: can not create client, bad configuration: did not find a proper configuration for private key
```

**Comment by varmax2511** [comment]
Hi @matthbak , since `private_key_password` is an optional parameter, unless its explicitly specified by a user in the provider configuration like `private_key_password = "${var.private_key_password}`, its not picked up from the environment variables.
 
We are considering enhancing the provider to pick `private_key_password` from environment variables as well when not explicitly specified in provider. This has been added to our backlog.

From our conversation earlier I understand that you are now unblocked. Please let us know if we can go ahead and close this ticket.

**Comment by matthbak** [comment]
Sounds good! Thanks for your help.
