### ISSUE TITLE
Compartment import of resource using oci_identity_compartment fails intermitently 

### ISSUE THREAD

**Issue by MarcinZablocki** [terraform-providers/terraform-provider-oci#725]
### Terraform Version

Terraform v0.11.13

### OCI Provider Version

+ provider.oci v3.17.0

### Description:
When importing a number of compartments to use in Terraform configuration, the process fails randomly with 409 error. Everything works fine on the subsequent run. Some compartments are imported, some are not. 

* oci_identity_compartment.compartment.12: Service error:CompartmentAlreadyExists. A compartment with name 'compartment_13' already exists.. http status code: 409. Opc request id: 6a6c2cccd75b74f8e16da379a0cf15d6/747E8FCE6E37CB3FE339906AC7912E42/40DA775021240BFC0B5A47DBD30FB4D5
* oci_identity_compartment.compartment[3]: 1 error(s) occurred:

* oci_identity_compartment.compartment.3: Service error:CompartmentAlreadyExists. A compartment with name 'compartment_4' already exists.. http status code: 409. Opc request id: 14078239e6d9fcbd42d69dd1c730aac2/26833DE5ADFCDCBED2D640A38C7B5830/2FC1E9A9D22E80E797FEA2E829E0FACF
* oci_identity_compartment.compartment[18]: 1 error(s) occurred:

* oci_identity_compartment.compartment.18: Service error:CompartmentAlreadyExists. A compartment with name 'compartment_19' already exists.. http status code: 409. Opc request id: d5cff0b07743e1883f83250013bac9d3/4F1E271DC58D0F60E9B3ED30D5BEE111/AE4382740CF7E3E39A2A24D87027DA45

### Terraform Plan

variable "count" {
    default = 20
}

resource "oci_identity_compartment" "compartment" {
    count = "${var.count}"
    compartment_id = "${var.tenancy_ocid}"
    description = "compartment_${count.index + 1}"
    name = "compartment_${count.index + 1}"
}

**Comment by rramge** [comment]
Hi Marcin,

It looks to me like you didn’t import the existing compartments before running “terraform apply”. Terraform doesn’t import resources by itself, you must do this manually.

terraform import <resource name> <ocid>

Hope this helps,

Ralf

**Comment by MarcinZablocki** [comment]
@rramge It actually does import compartments matching by name, it just fails for some. 

From: https://www.terraform.io/docs/providers/oci/r/identity_compartment.html
> For backwards compatibility, an existing compartment with the same name will be automatically imported into the state. Properties of the existing compartment will be updated to what is defined in the new configuration. This can cause a problem if multiple Terraform configurations are using the same compartment, but, for example, specify a different compartment description.

**Comment by kilokahn** [comment]
@MarcinZablocki thanks for reporting this. As you have rightly pointed out, we do support importing of compartments by default, unless you have specified `enable_delete = true`. I don't see that you have enabled that flag, so that shouldn't be the cause of the error; and if that was the case, you'd see an error to that effect. To take this forward, can you please share the debug logs (follow instructions at https://github.com/terraform-providers/terraform-provider-oci/blob/master/README.md#troubleshooting-the-provider) so that we can see the logic in play.

Can you also confirm if you have subcompartments for the existing compartments that you are attempting to import? Thanks!

**Comment by MarcinZablocki** [comment]
Unable to reproduce using 3.18.0
