### ISSUE TITLE
OKE Nodepools node metadata showing 0 nodes

### ISSUE THREAD

**Issue by harveylowndes** [terraform-providers/terraform-provider-oci#742]
### Terraform Version

v0.11.13

### OCI Provider Version

3.19.0

### Description:
We are creating an OKE cluster with 2 nodepools using terraform. We see them being created but the state file is not storing the nodes. The tf state file is showing an array of 0 nodes in the nodepool, when we actually have them. As a result, when we re-run a terraform plan, it wants us to recreated our nodepools. Running a terraform refresh against this removes the OKE cluster from the state file.

**Comment by kilokahn** [comment]
hey @harveylowndes - thanks for reporting the issue! We would need a little more information on the configuration that you used. 
1. Did this ever work before, or is this the first time you are trying this out?
2. Can you please share the config file and the debug logs (using instructions at https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider ) for your invocation? 

Our local testing seems to indicate no apparent problems, and there was a bug in provider version < 3.18.0 where specifying node_image_name used to cause a forceNew behavior (which has since been fixed).
This additional information will help us get to the next steps. Thanks!

**Comment by kilokahn** [comment]
hey @harveylowndes! we will wait for a few more days for you to respond and close it if we don't hear back. Thanks for understanding!

**Comment by afedorch** [comment]
please, feel free to reopen if the problem still exists. Thank you
