### ISSUE TITLE
Newly created OKE pool members showing status as 'UPDATING' 

### ISSUE THREAD

**Issue by wggit** [terraform-providers/terraform-provider-oci#756]
### Terraform Version

Terraform v0.11.13

provider.external v1.1.0
provider.oci v3.19.0

### OCI Provider Version

provider.oci v3.19.0

### Description:

Newly created OKE pool members showing status as 'UPDATING' - 

compute instance was created 32m4s ago and has not been seen in k8s nodes for 20m0s - verify network pre-requisites are correct, if so, try terminating the compute instance to trigger a replacement

Kubernetes Ver:v1.12.7
Shape: VM.Standard2.1
(Custom) Oracle-Linux-6
Total Worker Nodes:3
Nodes Per Subnet:1
Number of Subnets:3

**Comment by parrneet** [comment]
Hi @wggit 

Please share the terraform plan output, any Terraform configs, and the debug logs from terraform apply command to help investigate the issue.
To get the debug logs, prepend your terraform apply with options as below:
OCI_GO_SDK_DEBUG=v TF_LOG=DEBUG terraform apply

Also, since you were having issues with the version before, updating to the newer version might have caused the status to show as 'UPDATING'.

**Comment by wggit** [comment]
I am using latest version v1.12.7

**Comment by parrneet** [comment]
We would need more information to investigate this. Please iterate the steps taken to create the OKE pool including the config changes and logs.
My previous comment was regarding version upgrade, since you mentioned [here](https://github.com/terraform-providers/terraform-provider-oci/issues/755#issuecomment-485526030) that you were using an older version, upgrading to the latest version might be causing the 'UPDATING' state.

**Comment by codycushing** [comment]
Hello, please reopen if you are able to run again in debug mode and furnish more information. Thanks
