### ISSUE TITLE
Data Source oci_core_images

### ISSUE THREAD

**Issue by AndreaDiMonaco** [terraform-providers/terraform-provider-oci#762]
Hello,

I've a problem with the oci_core_images datasource.

<img width="250" alt="Screen Shot 2019-05-02 at 12 42 42" src="https://user-images.githubusercontent.com/14060726/57070483-dd6a2400-6cd7-11e9-81ff-421ae37bdd7e.png">

Basically when i try to show the "ID" output it shows the "time_created" value.

![Screen Shot 2019-05-02 at 11 34 33](https://user-images.githubusercontent.com/14060726/57067102-5b293200-6cce-11e9-8915-ded852006888.png)

<img width="403" alt="Screen Shot 2019-05-02 at 11 35 52" src="https://user-images.githubusercontent.com/14060726/57067165-7eec7800-6cce-11e9-9338-4cebb2699844.png">

Can you please check and fix this ? 

Many thanks,
Andrea.

**Comment by codycushing** [comment]
Hello, you are referencing a data source that returns a [list of images](https://www.terraform.io/docs/providers/oci/d/core_images.html#images), so you will need to use an index value to get a specific image before you can get the image id, like this:
```
${data.oci_core_images.InstanceImageOCID[0].id}
```
Because the value of this index will change over time as the service adds new images, this approach is not recommended for long term/stable infrastructure management. It is better to embed the actual image id value as a string. Here is an example of how to do that on a region agnostic basis:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/compute/image/variables.tf#L16
then to key into that value where you use the image value:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/compute/image/compute.tf#L18

**Comment by jamesob131** [comment]
I manually replaced the linux images with Oracle Linux 7.5 using this OCID: ocid1.image.oc1.iad.aaaaaaaageeenzyuxgia726xur4ztaoxbxyjlxogdhreu3ngfj2gji3bayda
As that is the recommended linux image from the documentation. For the windows image I replaced it with ocid1.image.oc1.iad.aaaaaaaazwjpcgqp7o4eh7okgmbobebdsmlvybxq5tskfojwsnwwxipnfntq which is the correct Windows image to use. The only terraform files you need to modify will be global.main.tf and nonpd.main.tf (assuming you are doing a non production deployment. Hope this helps!

**Comment by jamesob131** [comment]
^I thought this was referring to the JD Edwards terraform provisioner so please disregard if you're not  trying to implement that.

**Comment by AndreaDiMonaco** [comment]
Thank you cody and james!

i found that the correct def was
`data.oci_core_images.InstanceImageOCID.images.0.id`

it was the filter in the JDE template global.datasources.tf not working.

A.
