### ISSUE TITLE
oci_database_db_system auto_backup_enabled not applied

### ISSUE THREAD

**Issue by tr-patrick** [terraform-providers/terraform-provider-oci#768]
### Terraform Version

Terraform v0.11.13
+ provider.oci v3.24.1

### Description:

I created a database with the following. All good no issues. 

```
resource "oci_database_db_system" "prd-db11" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
  compartment_id      = "${var.compartment_ocid}"
  database_edition    = "${var.db_edition_prd-db11}"

  db_home {
    database {
      admin_password = "${var.db_admin_password_prd-db11}"
      db_name        = "${var.db_name_prd-db11}"
      character_set  = "${var.character_set_prd-db11}"
      ncharacter_set = "${var.n_character_set_prd-db11}"
      db_workload    = "${var.db_workload_prd-db11}"
      pdb_name       = "${var.pdb_name_prd-db11}"

      db_backup_config {
        auto_backup_enabled = false
      }
    }

    db_version   = "${var.db_version_prd-db11}"
    display_name = "${var.db_home_display_name_prd-db11}"
  
  }
  disk_redundancy = "${var.db_disk_redundancy_prd-db11}"
  shape           = "${var.db_system_shape_prd-db11}"
  subnet_id        = "${oci_core_subnet.L2AD1.id}"
  ssh_public_keys = ["${var.ssh_public_key}"]
  display_name    = "${var.db_system_display_name_prd-db11}"

  hostname                = "${var.hostname_prd-db11}"
  data_storage_percentage = "${var.data_storage_percentage_prd-db11}"
  data_storage_size_in_gb = "${var.data_storage_size_in_gb_prd-db11}"
  license_model           = "${var.license_model_prd-db11}"
  node_count              = "${var.node_count_prd-db11}"

}
```

When I do a terraform plan again it wants to change the value to something the same as when i created the resources

```
Terraform will perform the following actions:

  ~ module.prd-db-01.oci_database_db_system.instance
      db_home.0.database.0.db_backup_config.0.auto_backup_enabled: "" => "false"
```

I think well no problem. Give it a try........after 10 minutes i get an error

```
module.prd-db-01.oci_database_db_system.instance: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...z54fqahgze3yarnr7rccu2dt75yk3iz7mmzrkq, 10m30s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* module.prd-db-01.oci_database_db_system.instance: 1 error(s) occurred:

* oci_database_db_system.instance: Service error:IncorrectState. The existing Db System with ID ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljtrf4ghozme44b2pz54fqahgze3yarnr7rccu2dt75yk3iz7mmzrkq has a conflicting state of UPDATING.. http status code: 409. Opc request id: fbb20348a9382fda3387860319cadedb/911F14E477C093FB54C1BB47CECC5F09/8B4D9CDF49773CD589BAD4FD3AAE14B3

```

I tried this multiple times same issue. 

This means I have 2 issues
1. Why didn't the setting get written to the tfstate file for which it wants to do it again. 
2. Why does it break if you try it a second time

**Comment by tr-patrick** [comment]
Solution from issue 767 to add the following to your code

```
  lifecycle {
    ignore_changes  = ["db_home.0.db_version", "db_home.0.database.0.db_backup_config.0.auto_backup_enabled"]
    prevent_destroy = true
  }
```

**Comment by jearls** [comment]
One of the issues is that the provider is not actually setting the value.  If you use the API to set the `autoBackupEnabled` flag manually, this is fine.

Using the `oci_curl` script from the OCI API page, and assuming you have `jq` installed:
```
# fill in the compartment OCID, database system OCID, and region:
compartmentId=foo
dbSystemId=bar
region=us-phoenix-1
# create the update file in /tmp
echo '{"dbBackupConfig":{"autoBackupEnabled": false}}' > /tmp/update-auto-backup-enabled.json
# fetch the db home(s) on that database system
dbHomeIDs=$(oci_curl database.${region}.oraclecloud.com GET "/20160918/dbHomes?compartmentId=${compartmentId}&dbSystemId=${dbSystemId}" | jq -r 'map(.id) | join(" ")')
# for each db home...
for dbHomeId in ${dbHomeIDs}; do
    # fetch the database(s) on that db home
    databaseIDs=$(oci_curl database.${region}.oraclecloud.com GET "/20160918/databases?compartmentId=${compartmentId}&dbHomeId=${dbHomeId}" | jq -r 'map(.id) | join(" ")')
    # for each database...
    for databaseId in ${databaseIDs}; do
        oci_curl database.${region}.oraclecloud.com PUT /tmp/update-auto-backup-enabled.json "/20160918/databases/${databaseId}"
    done
done
```

**Comment by jearls** [comment]
BTW - unless something has changed since Terraform version 0.11.11, since the oci provider version 3.22, or unless "plan" ignores the lifecycle `ignore_changes` property, the workaround provided above does not work:

i created an override file for the (machine-generated) database configuration, as follows:
```hcl
resource "oci_database_db_system" "a201001db_aftm2ad1_phxx" {
  lifecycle {
    ignore_changes  = ["db_home.0.db_version", "db_home.0.database.0.db_backup_config.0.auto_backup_enabled"]
    prevent_destroy = true
  }
}
```
However, the "plan" output still includes:
```
  ~ oci_database_db_system.a201001db_aftm2ad1_phxx
      db_home.0.database.0.db_backup_config.0.auto_backup_enabled: "" => "false"
```

**Comment by jearls** [comment]
Apparently the `ignore_changes` does not work in an override file.  When I updated the machine-generated terraform files directly, terraform did not try to re-apply the change.

**Comment by ravitandonrt** [comment]
@jearls - The documentation states that it will merge the override block including ignore_changes: https://www.terraform.io/docs/configuration/override.html#merging-resource-and-data-blocks
Can you post your override file section on how you are overriding it. We will try to repro the same.

@tr-patrick 
Coming back to original issue on hand, there is a bug in the Update() method, where-in, we have to issue two updates, first for the DbSystem and second for the DbHome database on how the APIs are and the sub-resource requiring update on a different API.

The second update did not wait for DbSystem update to complete and reach `AVAILABLE`- see https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/database_db_system_resource.go#L770
So one will get 409 errors on subsequent updates, as also indicated in one of above errors that DbSystem is updating.

In the next release we are rolling out a fix that will provide a retry strategy on the second update, so you will see 409 errors but it will keep retrying so that it can apply the change and also update the state.

Until that fix lands, you can try either of following:
1. Add a ignore_changes to lifecycle to ignore dbHome updates that maybe causing this issue
2. Do separate update of configs for DbSystem & DbHome so that update requests are separated than Terraform doing in single apply.

Once the fix lands, we will update this issue so that you can remove the work-arounds.

**Comment by jearls** [comment]
I posted my exact override file above; here it is again:
```
resource "oci_database_db_system" "a201001db_aftm2ad1_phxx" {
  lifecycle {
    ignore_changes  = ["db_home.0.db_version", "db_home.0.database.0.db_backup_config.0.auto_backup_enabled"]
    prevent_destroy = true
  }
}
```

Also, not sure how this is an "enhancement" when the described functionality _does not occur_:  The autoBackupEnabled value _is not set_.

**Comment by tr-patrick** [comment]
@ravitandonrt
Thank you for updating. I'm able to work with the workaround right now. When we create the resource we set the autoBackupEnabled  to false which is what happens then with the resource. Because we also put it in the ignore changes we don't get any messages anymore. 

Will wait for the update and test again after the update.  Thanks for your help

**Comment by rcohenma** [comment]
We have fixed an issue that was causing unnecessary diffs on subsequent applies for auto_backup_enabled and recovery_window.
Version v3.26.0 has the fix: https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.26.0

Please give it a try.

**Comment by rcohenma** [comment]
We have also fixed the other issue where the update attempt timed out after 10 minutes.

The service does not allow multiple updates at the same time so we have to wait until the state of the dbSystem is no longer UPDATING before we try another update. We have added better logic to wait for this condition.

**Comment by tr-patrick** [comment]
@rcohenma

Looking good. Thank you for the changes
