### ISSUE TITLE
How to pass null values to source_details when creating a block volume

### ISSUE THREAD

**Issue by rhuesken** [terraform-providers/terraform-provider-oci#776]
```
$ terraform --version
Terraform v0.11.14
+ provider.oci v3.24.1
```

We use a single module to create the instance and the attached volumes. When creating an oci_core_volume, it is possible to specify the source_details. This element is optional, however its sub elements (type, id) are required. Initially, the volumes have been created without source_details, but now we try to use this module to restore a volume from a backup.

We have achieved this by adding the source details, to the module and providing the oci of the backup.  This process works, but when we try to create another instance, we do not provide a value (tried both "" and []) for the type and id in the source_details. This give the following message:

```
$ terraform plan

Error: module.prd-web-02.oci_core_volume.instance-data: expected source_details.0.type to be one of [volume volumeBackup], got 

$ terraform plan

Error: module.prd-web-02.oci_core_volume.instance-data: expected source_details.0.type to be one of [volume volumeBackup], got data
```

Is there a way to pass empty values to the source_details? Or is it possible to lift this restriction in the oci provider ? 

From the docs:

resource "oci_core_volume" "test_volume" {
    #Required
    availability_domain = "${var.volume_availability_domain}"
    compartment_id = "${var.compartment_id}"

    #Optional
    backup_policy_id = "${oci_core_backup_policy.test_backup_policy.id}"
    defined_tags = {"Operations.CostCenter"= "42"}
    display_name = "${var.volume_display_name}"
    freeform_tags = {"Department"= "Finance"}
    kms_key_id = "${oci_core_kms_key.test_kms_key.id}"
    size_in_gbs = "${var.volume_size_in_gbs}"
    size_in_mbs = "${var.volume_size_in_mbs}"
    source_details {
        #Required
        id = "${var.volume_source_details_id}"
        type = "${var.volume_source_details_type}"
    }
}

**Comment by ravitandonrt** [comment]
@rhuesken The `source_details` block is an optional field but it's sub properties are not and hence the errors you see are correct.

* https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/core_volume_resource.go#L89
* https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/core_volume_resource.go#L109

If you want to have empty `source_details`, the correct usage will be to remove that entire block and not setting it's sub properties to empty values. While Terraform does not have conditional blocks, dynamic blocks in new HCL2 syntax may help: https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks

To answer your question:
1. No, there is no way to pass empty values to `source_details`, empty values don't always mean optional. You will have to use newer syntax or use two different module variations based on scenario.
2. We cannot accept this change as the conditions are setup according to the values expected by API, by allowing empty values for sub-properties, it is hard to distinguish if it is because user wanted them skipped or empty is a valid value.

**Comment by rhuesken** [comment]
@ravitandonrt 
Thanks for the reply, this helps to find the right direction to look for solutions : terraform 0.12 and the corresponding oci provider.
