### ISSUE TITLE
terraform plan stuck with 'Refreshing state'

### ISSUE THREAD

**Issue by wggit** [terraform-providers/terraform-provider-oci#791]
### Terraform Version and Provider Version

terraform version
Terraform v0.11.13
+ provider.external v1.1.2
+ provider.null v2.1.2
**+ provider.oci v3.26.0**
+ provider.random v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

All data sources. It get stuck to any data source.

### Debug Output

2019/06/13 02:29:38 [DEBUG] Resource state not found for "data.oci_identity_regions.home-region": data.oci_identity_regions.home-region
2019/06/13 02:29:38 [DEBUG] ReferenceTransformer: "data.oci_identity_regions.home-region" references: []
2019/06/13 02:29:38 [TRACE] Graph after step *terraform.ReferenceTransformer:

data.oci_identity_regions.home-region - *terraform.NodeRefreshableDataResourceInstance
data.oci_identity_regions.home-region: Refreshing state...

### Expected Behavior

plan should move forward and execute

### Actual Behavior

plan hangs 

### Steps to Reproduce

1. `terraform plan`

**Comment by afedorch** [comment]
@wggit could you please share config file for us to reproduce the problem? if the problem exists for all data sources just create an example with one data source. Thanks!
It is hard to guess what could be the root cause without the configuration, but I would recommend checking env variables you are using for your configuration. Are you using the correct region?

**Comment by wggit** [comment]
Thank you. Issue was with user permissions who was running terraform plan.  Surprisingly plan was able complete in 30-40 minutes showing all modules.

**Comment by afedorch** [comment]
thanks for the fast response!
