### ISSUE TITLE
Is it possible to retrieve the tag keys and values from a resource manager stack via datasource?

### ISSUE THREAD

**Issue by drewncrew** [terraform-providers/terraform-provider-oci#916]
This Github template is intended for questions regarding the Terraform **Oracle Cloud Infrastructure** provider.

Before using this template, check whether your question is already answered in one of the following guides:
* [Frequently Asked Questions](https://www.terraform.io/docs/providers/oci/guides/faq.html)
* [Troubleshooting](https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html)

If you have a support request related to Oracle Cloud Infrastructure services, please [contact Oracle support](https://docs.cloud.oracle.com/iaas/Content/GSG/Tasks/contactingsupport.htm)

If you have a support request or question related to core Terraform functionality, please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by alexng-canuck** [comment]
@drewncrew , the Terraform OCI provider does not currently provide access to resource manager stacks. 

Since using Terraform to manage or look at resource manager stacks is not a typical or supported use case, can you share what your use case is? Do you have a need for these tags to be passed to some other downstream resource in Terraform?

Would it be possible to use the existing `oci` CLI to get the tags instead?

**Comment by afedorch** [comment]
@drewncrew  we will be closing this one, please let us know if you have other questions, thanks!
