### ISSUE TITLE
WAF Protection rules

### ISSUE THREAD

**Issue by dhoogfr** [terraform-providers/terraform-provider-oci#971]
When using a WAF policy, Oracle is providing a list of protection rules and makes recommendations on which one to implement. However, these seem to be not manageable via the oci_waas_waas_policy resource.
Within this resource, there is a section on custom protection rules, but the Oracle provided rules does not seem to fall under this part.
I tried to add them via the console and then show the terraform state after a refresh, but nothing is shown.

Is there a way to manage which of these provided protection rules are applied or get a list of which ones are recommended?

**Comment by parrneet** [comment]
Hi @dhoogfr 

Thank you for reporting this. 
The implementation is pending in Terraform due to some service side fixes that are pending. Please refer to [this existing issue](https://github.com/terraform-providers/terraform-provider-oci/issues/835) for more details.

I am closing this one as duplicate.
