### ISSUE TITLE
oci_core_volume_attachment device argument is not implemented correctly

### ISSUE THREAD

**Issue by lado936** [terraform-providers/terraform-provider-oci#988]
Terraform Version and Provider Version

Terraform v0.12.19

OCI v.3.59

 Affected Resource(s)

oci_core_volume_attachment

Configuration script:

resource "oci_core_volume_attachment" "mirth-connect-volume-attachment" {
    attachment_type         =   "paravirtualized"
    instance_id             =   oci_core_instance.instance.id
    volume_id               =   oci_core_volume.volume1.id
    device                  =   "dev/oracleoci/oraclevdp"
    display_name            =   "volume1"
    is_pv_encryption_in_transit_enabled =   "true"
}

expected behaviour:

run normally

actual behaviour:

Error: Service error:InvalidParameter. The volume cannot be attached to the instance ocid1.instance.oc1.phx.anyhqljrevgwwuic63hlehwpuutakxmymsazcxtt657iaaq4ghu36r6fa3hq because the specified device attribute dev/oracleoci/oraclevdp is invalid.. http status code: 400. 

except that, when i creat data source to find already attached volumes device atribute, output shows nothing.

Outputs:

volume =

but if i try to output for example volumes ocid it runs successfully.

i think device parameter is not implemented well, or am i missing something here?

**Comment by afedorch** [comment]
@lado936 
The error you shared is the service response for the `oci_core_volume_attachment` resource configuration.
It means that you should get the same error for this configuration across all the surfaces (for example console, CLI)


Please take a look if the example of the configuration in provider repo could help:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/compute/instance/instance.tf#L121


To verify the expected behavior for your configuration make sure that you follow all the service requirements:

Consistent device paths are supported on instances when all of the following things are true:
https://docs.cloud.oracle.com/en-us/iaas/Content/Block/Concepts/overview.htm

https://docs.cloud.oracle.com/en-us/iaas/Content/Block/References/consistentdevicepaths.htm

Thanks!
