### ISSUE TITLE
Attach custom security list to existent subnet

### ISSUE THREAD

**Issue by antonio-petricca** [terraform-providers/terraform-provider-oci#995]
Hi, my company provided me a subnet OCID to provision some services. 

I'am not an admin, but I can manage resources inside my compartment.

I should add a custom security list to that subnet by terraform, but  I don't know how to accomplish this.

Could you help me?

Thank you so much!
Antonio

**Comment by alexng-canuck** [comment]
Hi @antonio-petricca ,

Is the subnet created and managed by you? Or is it created and managed by someone else?

If it is created by you, then you could import it into Terraform using `terraform import` command and update it so that it accepts the new custom security list OCID.

See https://github.com/terraform-providers/terraform-provider-oci/blob/41440f6d85de75a76b46b7da1264e6d914f8111d/examples/networking/subnet/subnet.tf#L50

In the above example, an `oci_core_subnet` can be associated with one or more custom security list OCIDs.

If the subnet resource is managed by someone else, then you could ask that person to add your custom security list to the subnet. I wouldn't recommend using Terraform to manage resources owned by other people, because you could unintentionally overwrite their configuration with your own configuration unless you are very careful.

Unfortunately there is no way to just specify the subnet OCID to a custom security list. The association has to happen in the subnet's configuration.

**Comment by alexng-canuck** [comment]
Closing due to lack of response.
